// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20251204184803_Add-CardPosition")]
    partial class AddCardPosition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("DAL.Entities.CardState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CardIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GameStateId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFaceUp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameStateId");

                    b.ToTable("CardStates");
                });

            modelBuilder.Entity("DAL.Entities.GameState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentFlippedCardId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurrentTurnId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GameStartTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGameOver")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSinglePlayer")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Player1Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Player1Score")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("Player2Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Player2Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentFlippedCardId");

                    b.HasIndex("CurrentTurnId");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.ToTable("GameStates");
                });

            modelBuilder.Entity("DAL.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DAL.Entities.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameStateId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameStateId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("DAL.Entities.CardState", b =>
                {
                    b.HasOne("DAL.Entities.GameState", "GameState")
                        .WithMany("Cards")
                        .HasForeignKey("GameStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameState");
                });

            modelBuilder.Entity("DAL.Entities.GameState", b =>
                {
                    b.HasOne("DAL.Entities.CardState", "CurrentFlippedCard")
                        .WithMany()
                        .HasForeignKey("CurrentFlippedCardId");

                    b.HasOne("DAL.Entities.Player", "CurrentTurn")
                        .WithMany()
                        .HasForeignKey("CurrentTurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id");

                    b.Navigation("CurrentFlippedCard");

                    b.Navigation("CurrentTurn");

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });

            modelBuilder.Entity("DAL.Entities.Score", b =>
                {
                    b.HasOne("DAL.Entities.GameState", "GameState")
                        .WithMany()
                        .HasForeignKey("GameStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameState");
                });

            modelBuilder.Entity("DAL.Entities.GameState", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
